module.exports = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{ts,tsx,js,jsx}",
    "./src/components/**/*.{ts,tsx,js,jsx}",
    "./src/pages/**/*.{ts,tsx,js,jsx}",
    "./src/**/*.{ts,tsx}",
    "./public/**/*.{html,js}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        "edu-primary": "#00288e",
        "edu-primary-container": "#1e40af",
        "edu-on-primary": "#ffffff",
        "edu-secondary": "#5c5f61",
        "edu-tertiary": "#003d27",
        "edu-tertiary-container": "#3fd298",
        "edu-on-tertiary": "#ffffff",
        "edu-background": "#f8f9ff",
        "edu-on-background": "#0b1c30",
        "edu-surface": "#f8f9ff",
        "edu-on-surface": "#0b1c30",
        "edu-surface-container-low": "#eff4ff",
        "edu-surface-container": "#e5eeff",
        "edu-surface-container-high": "#dce9ff",
        "edu-surface-container-highest": "#d3e4fe",
        "edu-outline": "#757684",
        "edu-error": "#ba1a1a",
        "edu-on-error": "#ffffff",
        "edu-surface-variant": "#d3e4fe",
        "edu-on-surface-variant": "#444653",
        "edu-surface-bright": "#f8f9ff",
        "edu-surface-dim": "#cbdbf5",
        "edu-on-primary-container": "#ffffff",
        "edu-on-tertiary-container": "#002113",
        "edu-on-secondary-container": "#191c1e",
        "edu-on-error-container": "#93000a",
        "edu-inverse-surface": "#213145",
        "edu-inverse-on-surface": "#eaf1ff",
        "edu-inverse-primary": "#b8c4ff",
      },
      borderRadius: {
        lg: "0",
        md: "0",
        sm: "0",
      },
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
      },
      keyframes: {
        "accordion-down": { from: { height: 0 }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: 0 } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
